name: 'FibBot'
description: 'A GitHub Action to calculate Fibonacci numbers from PR content.'
inputs:
  enable_fib:
    description: 'Enable Fibonacci calculation'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum number for Fibonacci calculation'
    required: true
    default: '100'
runs:
  using: 'docker'
  image: 'Dockerfile'