name: Test FibBot
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
       image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run FibBot
        uses: ./ # Path to the action 
