name: Test FibBot

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v

      - name: Build
        run: cargo build --release
      - name: Run FibBot
        uses: ./
        with:
          enable_fib: true
          max_threshold: 250

      - name: Set up Docker
        run: |
          docker build -t fibbot .

      - name: Run FibBot Docker container
        run: |
          docker run \
            -e INPUT_ENABLE_FIB=true \
            -e INPUT_MAX_THRESHOLD=1000 \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_API_URL=https://api.github.com \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_REF=${{ github.head_ref }} \
            fibbot
