name: Test FibBot
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
       image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run FibBot
      - uses: ./
